# Use Vagrant configuration version 2
Vagrant.configure("2") do |config|

  # Base OS image for all VMs
  config.vm.box = "bento/ubuntu-24.04"

  # VirtualBox-specific configuration
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"   # Allocate 1 GB RAM
    vb.cpus = 1          # Allocate 1 CPU core
  end

  # --------------------------------------------------
  # Server node (K3s controller)
  # --------------------------------------------------
  config.vm.define "yilinS" do |server|

    # Set Linux hostname
    server.vm.hostname = "yilinS"

    # Create a private network interface (eth1)
    # This is used for Kubernetes internal communication
    server.vm.network "private_network", ip: "192.168.56.110"

    # Run shell provisioner during `vagrant up`
    # Pass "server" as argument to the script
    server.vm.provision "shell",
      path: "scripts/install_k3s.sh",
      args: ["server"]
  end


end