# Use Vagrant configuration version 2
Vagrant.configure("2") do |config|

  # Base OS image for all VMs
  config.vm.box = "bento/ubuntu-24.04"

  # VirtualBox-specific configuration
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"   # Allocate 1 GB RAM
    vb.cpus = 1          # Allocate 1 CPU core
  end


  # --------------------------------------------------
  # Server node (K3s controller)
  # --------------------------------------------------
  config.vm.define "yilinS" do |server|

    # Set Linux hostname
    server.vm.hostname = "yilinS"

    # Create a private network interface (eth1)
    # This is used for Kubernetes internal communication
    server.vm.network "private_network", ip: "192.168.56.110"

    # Run shell provisioner during `vagrant up`
    # Pass "server" as argument to the script
    server.vm.provision "shell",
      path: "scripts/install_k3s.sh",
      args: ["server"]
  end


  # --------------------------------------------------
  # Worker node (K3s agent)
  # --------------------------------------------------
  config.vm.define "yilinSW" do |worker|

    # Set Linux hostname
    worker.vm.hostname = "yilinSW"

    # Same private network, different IP
    worker.vm.network "private_network", ip: "192.168.56.111"

    # Run the same script, but as worker
    worker.vm.provision "shell",
      path: "scripts/install_k3s.sh",
      args: ["worker"]
  end

end


### NOTES ###
# do ... end: -> like {} -> defines a Block of code. It's a chunk of code that you are passing into the method to be executed.
# |config|: This is the Block Variable (parameter).
  # When Vagrant.configure runs, it creates a settings object and "yields" it to your block.
  # Inside the block, you give that object a name: config.
  # Whatever changes you make to config inside the block are applied to the final setup.

# server.vm.network "private_network", ip: "..."
  # Concept: Method with Mixed Arguments (Positional + Keyword).
  # "private_network": This is a Positional Argument. It's the first input, and order matters. It tells the function what type of network to create.
  # ip: "192.168.56.110": This is a Keyword Argument (Named Parameter).
  # Ruby allows key: value syntax at the end of a function call.
  # This is specific configuration data for the network. because you labelled it ip:, the function knows exactly what this string is for, regardless of order.