Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.hostname = "yilinS"
  config.vm.network "private_network", ip: "192.168.56.110"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024" # K3s is lightweight, 1GB is usually enough for Part 1
    vb.cpus = 1
  end

  config.vm.provision "shell", path: "scripts/install_k3s.sh"
end
